import { Restaurant, Table, MenuItem, Reservation, QueueToken, WaitlistEntry, KitchenTicket, NotificationItem } from './types';
import { getTodayDateString } from './utils';

export const INITIAL_TABLES: Table[] = [
  {
    id: 'tbl-1',
    tableNumber: 'T-1',
    capacity: 2,
    section: 'WINDOW',
    sectionName: 'Window Seat (Ground Floor)',
    floor: 'Ground Floor',
    status: 'AVAILABLE',
    isAccessible: true,
    notes: 'Romantic garden view, ambient lighting',
  },
  {
    id: 'tbl-2',
    tableNumber: 'T-2',
    capacity: 2,
    section: 'INDOOR',
    sectionName: 'Indoor Cozy Corner',
    floor: 'Ground Floor',
    status: 'AVAILABLE',
    isAccessible: true,
    notes: 'Quiet corner, ideal for dates and quick dining',
  },
  {
    id: 'tbl-3',
    tableNumber: 'T-3',
    capacity: 4,
    section: 'WINDOW',
    sectionName: 'Window Panorama 4-Seat',
    floor: 'Ground Floor',
    status: 'AVAILABLE',
    isAccessible: true,
    notes: 'Scenic boulevard view, cushioned booth seating',
  },
  {
    id: 'tbl-4',
    tableNumber: 'T-4',
    capacity: 4,
    section: 'AC_SECTION',
    sectionName: 'Central AC Family Table',
    floor: 'Ground Floor',
    status: 'OCCUPIED',
    isAccessible: true,
    notes: 'Spacious central section with child seats support',
  },
  {
    id: 'tbl-5',
    tableNumber: 'T-5',
    capacity: 6,
    section: 'OUTDOOR',
    sectionName: 'Garden Patio Gazebo',
    floor: 'Outdoor Patio',
    status: 'AVAILABLE',
    isAccessible: false,
    notes: 'Open-air fairy-light patio, live acoustic background',
  },
  {
    id: 'tbl-6',
    tableNumber: 'T-6',
    capacity: 8,
    section: 'VIP_LOUNGE',
    sectionName: 'Executive VIP Lounge',
    floor: '1st Floor',
    status: 'AVAILABLE',
    isAccessible: false,
    notes: 'Private partition, dedicated attendant, plush leather couches',
  },
  {
    id: 'tbl-7',
    tableNumber: 'T-7',
    capacity: 4,
    section: 'INDOOR',
    sectionName: 'Indoor Dining Table',
    floor: 'Ground Floor',
    status: 'AVAILABLE',
    isAccessible: true,
    notes: 'Close to buffet & beverage counter',
  },
  {
    id: 'tbl-8',
    tableNumber: 'T-8',
    capacity: 2,
    section: 'OUTDOOR',
    sectionName: 'Balcony Terrace 2-Seat',
    floor: '1st Floor Terrace',
    status: 'RESERVED',
    isAccessible: false,
    notes: 'Breezy rooftop overlook',
  },
];

export const INITIAL_MENU: MenuItem[] = [
  // Starters
  {
    id: 'menu-1',
    name: 'Paneer Tikka Angara',
    category: 'Starters',
    price: 180,
    description: 'Char-grilled cottage cheese cubes marinated in Kashmiri chili and tandoori spices.',
    image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=500&auto=format&fit=crop&q=80',
    dietary: 'VEG',
    spiceLevel: 'Medium',
    prepTimeMinutes: 15,
    isPopular: true,
    calories: 320,
  },
  {
    id: 'menu-2',
    name: 'Crispy Peri-Peri Corn Kernels',
    category: 'Starters',
    price: 140,
    description: 'Golden sweet corn wok-tossed with peri-peri dust, bell peppers, and fresh cilantro.',
    image: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=500&auto=format&fit=crop&q=80',
    dietary: 'VEG',
    spiceLevel: 'Spicy',
    prepTimeMinutes: 10,
    calories: 240,
  },
  {
    id: 'menu-3',
    name: 'Smoky Tandoori Chicken Wings (6 pcs)',
    category: 'Starters',
    price: 240,
    description: 'Succulent chicken wings roasted over charcoal coals with garlic mint glaze.',
    image: 'https://images.unsplash.com/photo-1527477321055-43615852573d?w=500&auto=format&fit=crop&q=80',
    dietary: 'NON_VEG',
    spiceLevel: 'Spicy',
    prepTimeMinutes: 18,
    isPopular: true,
    calories: 420,
  },

  // Dosa
  {
    id: 'menu-4',
    name: 'Classic Butter Masala Dosa',
    category: 'Dosa',
    price: 120,
    description: 'Crispy fermented crepe stuffed with spiced potato mash, served with coconut chutney & piping sambar.',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=500&auto=format&fit=crop&q=80',
    dietary: 'VEG',
    spiceLevel: 'Mild',
    prepTimeMinutes: 12,
    isPopular: true,
    calories: 340,
  },
  {
    id: 'menu-5',
    name: 'Mysore Ghee Roast Dosa',
    category: 'Dosa',
    price: 150,
    description: 'Golden crisp dosa smeared with fiery Mysore red chutney and pure desi ghee.',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&auto=format&fit=crop&q=80',
    dietary: 'VEG',
    spiceLevel: 'Spicy',
    prepTimeMinutes: 12,
    calories: 390,
  },

  // Pizza & Italian
  {
    id: 'menu-6',
    name: 'Truffle Mushroom & Mozzarella Pizza',
    category: 'Pizza',
    price: 320,
    description: 'Wood-fired hand-stretched sourdough, wild portobello mushrooms, black truffle oil, mozzarella.',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500&auto=format&fit=crop&q=80',
    dietary: 'VEG',
    spiceLevel: 'Mild',
    prepTimeMinutes: 15,
    isPopular: true,
    calories: 680,
  },
  {
    id: 'menu-7',
    name: 'Paneer Makhani Sourdough Pizza',
    category: 'Pizza',
    price: 290,
    description: 'Rich tomato makhani sauce base, charred paneer cubes, roasted bell peppers, mozzarella.',
    image: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=500&auto=format&fit=crop&q=80',
    dietary: 'VEG',
    spiceLevel: 'Medium',
    prepTimeMinutes: 15,
    calories: 650,
  },

  // Burgers
  {
    id: 'menu-8',
    name: 'Smoky BBQ Veg Royale Burger',
    category: 'Burgers',
    price: 160,
    description: 'Crispy veggie patty, smoked cheddar, caramelized onions, BBQ mayo in toasted brioche.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&auto=format&fit=crop&q=80',
    dietary: 'VEG',
    spiceLevel: 'Mild',
    prepTimeMinutes: 12,
    calories: 520,
  },
  {
    id: 'menu-9',
    name: 'Crispy Truffle Chicken Burger',
    category: 'Burgers',
    price: 210,
    description: 'Buttermilk fried chicken breast, truffle aioli, pickled jalapenos, iceberg lettuce.',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=500&auto=format&fit=crop&q=80',
    dietary: 'NON_VEG',
    spiceLevel: 'Medium',
    prepTimeMinutes: 15,
    isPopular: true,
    calories: 590,
  },

  // Main Course
  {
    id: 'menu-10',
    name: 'Dal Makhani with Garlic Naan Combo',
    category: 'Main Course',
    price: 230,
    description: 'Slow-cooked black lentils simmered for 24 hours with butter and cream, served with 2 hot garlic naans.',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=500&auto=format&fit=crop&q=80',
    dietary: 'VEG',
    spiceLevel: 'Mild',
    prepTimeMinutes: 15,
    isPopular: true,
    calories: 610,
  },
  {
    id: 'menu-11',
    name: 'Butter Chicken with Amritsari Kulcha',
    category: 'Main Course',
    price: 280,
    description: 'Tender tandoori chicken cooked in velvety cashew-tomato gravy, paired with stuffed kulcha.',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=500&auto=format&fit=crop&q=80',
    dietary: 'NON_VEG',
    spiceLevel: 'Medium',
    prepTimeMinutes: 18,
    calories: 740,
  },

  // Beverages
  {
    id: 'menu-12',
    name: 'Artisanal Cold Coffee Frappe',
    category: 'Beverages',
    price: 90,
    description: 'Blended espresso, Belgian chocolate sauce, vanilla gelato, crowned with whipped foam.',
    image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=500&auto=format&fit=crop&q=80',
    dietary: 'VEG',
    prepTimeMinutes: 6,
    isPopular: true,
    calories: 220,
  },
  {
    id: 'menu-13',
    name: 'Royal Mango Kesar Lassi',
    category: 'Beverages',
    price: 80,
    description: 'Thick creamy yogurt churned with Alphonso mango pulp and Kashmiri saffron threads.',
    image: 'https://images.unsplash.com/photo-1571006682878-43d99723ec02?w=500&auto=format&fit=crop&q=80',
    dietary: 'VEG',
    prepTimeMinutes: 5,
    calories: 190,
  },
  {
    id: 'menu-14',
    name: 'Fresh Mint Mojito',
    category: 'Beverages',
    price: 95,
    description: 'Crushed garden mint, Sicilian lime wedges, sparkling soda over crushed crystal ice.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=500&auto=format&fit=crop&q=80',
    dietary: 'VEGAN',
    prepTimeMinutes: 5,
    calories: 90,
  },

  // Desserts
  {
    id: 'menu-15',
    name: 'Warm Gulab Jamun Sundae',
    category: 'Desserts',
    price: 140,
    description: 'Warm melt-in-mouth gulab jamuns topped with rich Madagascar vanilla bean ice cream and pistachios.',
    image: 'https://images.unsplash.com/photo-1589119908995-c6837fa14d48?w=500&auto=format&fit=crop&q=80',
    dietary: 'VEG',
    prepTimeMinutes: 6,
    isPopular: true,
    calories: 360,
  },
  {
    id: 'menu-16',
    name: 'Sizzling Belgian Brownie with Gelato',
    category: 'Desserts',
    price: 190,
    description: 'Fudgy walnut brownie served on a sizzling hot plate with hot chocolate fudge and vanilla gelato.',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=500&auto=format&fit=crop&q=80',
    dietary: 'VEG',
    prepTimeMinutes: 8,
    calories: 480,
  },

  // Combos
  {
    id: 'menu-17',
    name: 'Family Feast Combo (Serves 4)',
    category: 'Combos',
    price: 899,
    description: 'Includes 2 Starters, 2 Main Dishes, 4 Garlic Naans, 1 Pizza, and 4 Cold Coffees / Lassis.',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=500&auto=format&fit=crop&q=80',
    dietary: 'VEG',
    prepTimeMinutes: 20,
    isPopular: true,
    calories: 1800,
  },
  {
    id: 'menu-18',
    name: 'Couple Romantic Dinner Platter',
    category: 'Combos',
    price: 549,
    description: '1 Artisanal Pizza, 1 Starter, 2 Mocktails, and 1 Sizzling Brownie dessert.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=500&auto=format&fit=crop&q=80',
    dietary: 'VEG',
    prepTimeMinutes: 18,
    calories: 1100,
  },
];

export const INITIAL_RESTAURANTS: Restaurant[] = [
  {
    id: 'rest-1',
    name: 'Spice Garden',
    tagline: 'Authentic Flavors, Fine Dining & Contemporary Delights',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.9,
    reviewCount: 1248,
    cuisines: ['North Indian', 'South Indian', 'Artisanal Pizza', 'Continental', 'Beverages'],
    location: 'Indiranagar 100ft Road, Bengaluru',
    address: '42, 100 Feet Rd, HAL 2nd Stage, Indiranagar, Bengaluru, Karnataka 560038',
    phone: '+91 80 4123 9870',
    openingTime: '11:00',
    closingTime: '23:00',
    slotDurationMinutes: 90,
    cleaningBufferMinutes: 15,
    gracePeriodMinutes: 15,
    depositRequired: true,
    depositAmount: 200,
    tables: INITIAL_TABLES,
    menu: INITIAL_MENU,
    currentOccupancy: 68,
    totalTables: 8,
    availableTables: 6,
    estimatedQueueWaitMinutes: 15,
    offers: [
      {
        code: 'PREORDER10',
        title: '10% OFF on Pre-Orders',
        description: 'Save 10% on your entire food bill when you pre-order during reservation.',
        discountPercent: 10,
      },
      {
        code: 'FEAST100',
        title: '₹100 OFF on ₹799+',
        description: 'Flat ₹100 instant discount on orders above ₹799.',
        discountFlat: 100,
        minOrder: 799,
      },
      {
        code: 'FREEBEV',
        title: 'Free Beverage with Family Combo',
        description: 'Get an extra Cold Coffee or Lassi with any Combo order.',
        discountFlat: 90,
        minOrder: 600,
      },
    ],
  },
  {
    id: 'rest-2',
    name: 'Urban Bistro & Rooftop Cafe',
    tagline: 'Artisanal Brews, Sourdough Pizzas & Sunset Views',
    image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.8,
    reviewCount: 890,
    cuisines: ['European', 'Italian', 'Specialty Coffee', 'Desserts'],
    location: 'Koramangala 4th Block, Bengaluru',
    address: '88, 5th Main Rd, Koramangala 4th Block, Bengaluru, Karnataka 560034',
    phone: '+91 80 4455 2211',
    openingTime: '10:00',
    closingTime: '23:30',
    slotDurationMinutes: 90,
    cleaningBufferMinutes: 15,
    gracePeriodMinutes: 15,
    depositRequired: false,
    depositAmount: 0,
    tables: INITIAL_TABLES.slice(0, 6),
    menu: INITIAL_MENU.filter(i => ['Pizza', 'Burgers', 'Beverages', 'Desserts'].includes(i.category)),
    currentOccupancy: 80,
    totalTables: 6,
    availableTables: 2,
    estimatedQueueWaitMinutes: 25,
    offers: [
      {
        code: 'BISTRO15',
        title: '15% Off Sourdough Pizzas',
        description: 'Exclusive on all pre-booked tables.',
        discountPercent: 15,
      },
    ],
  },
  {
    id: 'rest-3',
    name: 'The Coastal Bay Grill',
    tagline: 'Fresh Coastal Seafood & Charcoal Barbecue',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.7,
    reviewCount: 650,
    cuisines: ['Coastal Seafood', 'Mangalorean', 'Barbecue', 'Tandoor'],
    location: 'Church Street, Bengaluru',
    address: '15, Church St, Shanthala Nagar, Ashok Nagar, Bengaluru, Karnataka 560001',
    phone: '+91 80 4999 8833',
    openingTime: '12:00',
    closingTime: '23:00',
    slotDurationMinutes: 90,
    cleaningBufferMinutes: 15,
    gracePeriodMinutes: 15,
    depositRequired: true,
    depositAmount: 250,
    tables: INITIAL_TABLES.slice(0, 6),
    menu: INITIAL_MENU,
    currentOccupancy: 50,
    totalTables: 6,
    availableTables: 3,
    estimatedQueueWaitMinutes: 10,
    offers: [
      {
        code: 'COASTAL10',
        title: '10% Flat Discount',
        description: 'Valid on all dinner pre-bookings.',
        discountPercent: 10,
      },
    ],
  },
];

export const INITIAL_RESERVATIONS: Reservation[] = [
  {
    reservationId: 'QB-2026-1048',
    customerId: 'cust-demo-1',
    customerName: 'Rahul Sharma',
    customerPhone: '+91 98765 43210',
    customerEmail: 'rahul.sharma@example.com',
    restaurantId: 'rest-1',
    restaurantName: 'Spice Garden',
    tableId: 'tbl-3',
    tableNumber: 'T-3',
    date: getTodayDateString(),
    startTime: '19:30',
    endTime: '21:00',
    guestCount: 4,
    tablePreference: 'WINDOW',
    specialRequests: 'Window seat for family celebration, high chair requested.',
    preOrderItems: [
      { item: INITIAL_MENU[3], quantity: 2 }, // Masala Dosa
      { item: INITIAL_MENU[0], quantity: 1 }, // Paneer Tikka
      { item: INITIAL_MENU[11], quantity: 2 }, // Cold Coffee
    ],
    preOrderTotal: 600,
    discountAmount: 60, // 10% off
    finalAmount: 540,
    depositRequired: true,
    depositAmount: 200,
    paymentStatus: 'PAID',
    paymentMethod: 'UPI',
    bookingStatus: 'CONFIRMED',
    qrCodeData: 'QUEUEBITE:RES:QB-2026-1048:T-3:2026-08-16:19:30',
    prepStartTime: '19:15',
    prepStatus: 'SCHEDULED',
    gracePeriodMinutes: 15,
    createdAt: '2026-08-16T08:15:00.000Z',
    updatedAt: '2026-08-16T08:15:00.000Z',
  },
  {
    reservationId: 'QB-2026-1042',
    customerId: 'cust-demo-2',
    customerName: 'Ananya Verma',
    customerPhone: '+91 98111 22334',
    customerEmail: 'ananya.v@example.com',
    restaurantId: 'rest-1',
    restaurantName: 'Spice Garden',
    tableId: 'tbl-8',
    tableNumber: 'T-8',
    date: getTodayDateString(),
    startTime: '20:00',
    endTime: '21:30',
    guestCount: 2,
    tablePreference: 'OUTDOOR',
    preOrderItems: [
      { item: INITIAL_MENU[5], quantity: 1 }, // Truffle Pizza
      { item: INITIAL_MENU[13], quantity: 2 }, // Fresh Mint Mojito
    ],
    preOrderTotal: 510,
    discountAmount: 51,
    finalAmount: 459,
    depositRequired: true,
    depositAmount: 200,
    paymentStatus: 'PAID',
    paymentMethod: 'CARD',
    bookingStatus: 'CONFIRMED',
    qrCodeData: 'QUEUEBITE:RES:QB-2026-1042:T-8:2026-08-16:20:00',
    prepStartTime: '19:45',
    prepStatus: 'SCHEDULED',
    gracePeriodMinutes: 15,
    createdAt: '2026-08-16T07:45:00.000Z',
    updatedAt: '2026-08-16T07:45:00.000Z',
  },
  {
    reservationId: 'QB-2026-0995',
    customerId: 'cust-demo-3',
    customerName: 'Vikram Mehta',
    customerPhone: '+91 97234 56789',
    customerEmail: 'vikram.m@example.com',
    restaurantId: 'rest-1',
    restaurantName: 'Spice Garden',
    tableId: 'tbl-4',
    tableNumber: 'T-4',
    date: getTodayDateString(),
    startTime: '13:00',
    endTime: '14:30',
    guestCount: 4,
    tablePreference: 'AC_SECTION',
    preOrderItems: [
      { item: INITIAL_MENU[9], quantity: 2 }, // Dal Makhani Combo
      { item: INITIAL_MENU[12], quantity: 2 }, // Mango Lassi
    ],
    preOrderTotal: 620,
    discountAmount: 62,
    finalAmount: 558,
    depositRequired: true,
    depositAmount: 200,
    paymentStatus: 'PAID',
    paymentMethod: 'UPI',
    bookingStatus: 'SEATED',
    qrCodeData: 'QUEUEBITE:RES:QB-2026-0995:T-4:2026-08-16:13:00',
    prepStartTime: '12:45',
    prepStatus: 'SERVED',
    checkInTime: '12:55',
    seatedTime: '13:02',
    gracePeriodMinutes: 15,
    createdAt: '2026-08-15T18:30:00.000Z',
    updatedAt: '2026-08-16T13:02:00.000Z',
  },
];

export const INITIAL_QUEUE_TOKENS: QueueToken[] = [
  {
    tokenId: 'T-041',
    restaurantId: 'rest-1',
    customerName: 'Deepak Rao',
    customerPhone: '+91 99001 12233',
    guestCount: 2,
    tablePreference: 'ANY',
    status: 'CALLING',
    joinedAt: '2026-08-16T09:05:00.000Z',
    estimatedWaitMinutes: 5,
    assignedTableId: 'tbl-1',
    assignedTableNumber: 'T-1',
    preOrderItems: [{ item: INITIAL_MENU[0], quantity: 1 }],
    preOrderTotal: 180,
  },
  {
    tokenId: 'T-042',
    restaurantId: 'rest-1',
    customerName: 'Pooja Iyer',
    customerPhone: '+91 98866 55443',
    guestCount: 4,
    tablePreference: 'WINDOW',
    status: 'WAITING',
    joinedAt: '2026-08-16T09:15:00.000Z',
    estimatedWaitMinutes: 15,
  },
];

export const INITIAL_WAITLIST: WaitlistEntry[] = [
  {
    waitlistId: 'WL-284',
    restaurantId: 'rest-1',
    customerName: 'Sanjay Deshmukh',
    customerPhone: '+91 98220 33445',
    customerEmail: 'sanjay.d@example.com',
    guestCount: 6,
    preferredDate: getTodayDateString(),
    preferredTime: '20:30',
    tablePreference: 'OUTDOOR',
    status: 'WAITING',
    joinedAt: '2026-08-16T08:45:00.000Z',
    estimatedWaitMinutes: 25,
  },
];

export const INITIAL_KITCHEN_TICKETS: KitchenTicket[] = [
  {
    ticketId: 'KT-1048',
    sourceType: 'RESERVATION',
    sourceId: 'QB-2026-1048',
    customerName: 'Rahul Sharma',
    tableNumber: 'T-3',
    items: [
      { item: INITIAL_MENU[3], quantity: 2 },
      { item: INITIAL_MENU[0], quantity: 1 },
      { item: INITIAL_MENU[11], quantity: 2 },
    ],
    scheduledPrepTime: '19:15',
    targetServeTime: '19:30',
    prepDurationMinutes: 15,
    status: 'SCHEDULED',
    specialNotes: 'Guest arrival at 7:30 PM. Start prep at 7:15 PM sharp.',
    createdAt: '2026-08-16T08:15:00.000Z',
  },
  {
    ticketId: 'KT-0995',
    sourceType: 'RESERVATION',
    sourceId: 'QB-2026-0995',
    customerName: 'Vikram Mehta',
    tableNumber: 'T-4',
    items: [
      { item: INITIAL_MENU[9], quantity: 2 },
      { item: INITIAL_MENU[12], quantity: 2 },
    ],
    scheduledPrepTime: '12:45',
    targetServeTime: '13:00',
    prepDurationMinutes: 15,
    status: 'SERVED',
    completedAt: '2026-08-16T13:10:00.000Z',
    createdAt: '2026-08-15T18:30:00.000Z',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Booking Confirmed 🎉',
    message: 'Your reservation QB-2026-1048 for 4 guests at Spice Garden is confirmed for today at 7:30 PM.',
    type: 'CONFIRMATION',
    timestamp: '2026-08-16T08:15:00.000Z',
    read: false,
    bookingId: 'QB-2026-1048',
  },
  {
    id: 'notif-2',
    title: 'Pre-Order Received 👨‍🍳',
    message: 'Kitchen scheduled prep at 7:15 PM for your reservation at Table T-3.',
    type: 'KITCHEN_ALERT',
    timestamp: '2026-08-16T08:16:00.000Z',
    read: false,
    bookingId: 'QB-2026-1048',
  },
];
